### ISSUE TITLE
ArcGIS API for JavaScript 4.X and ECMAScript 2015 (ES6)

### ISSUE THREAD

**Issue by sanmolhec** [hhkaos/awesome-arcgis#11]
Hi, in my organization we are working on a project for a web application where we are using JS API 4. X.

In a couple of talks given from ESRI Spain, we were told to use the **benefits** of **ES6** with the ArcGIS API for JavaScript 4.

Among other things we were advised to use the **promises**, which seems very useful and a **big improvement** over API 3. XX.

But the fact is that when we enter the examples of API 4, we don't use the ES6 syntax (all examples are made with original AMD syntax), and looking for more information on the web, the most we have found is this page [http://odoe.net/blog/use-es2015-with-arcgis-api-for-javascript/](http://odoe.net/blog/use-es2015-with-arcgis-api-for-javascript/) of Rene Rubalcava, which is no small but we would like to have more.

So we ask you if you can give us information or link's pages where there are examples, best practisses... And it would be a great advance if the API Reference code examples were written with ES6, or if there were examples with the two syntax alternatives.

Thank you very much. 

Regards, Héctor.

**Comment by jgravois** [comment]
@odoe, @noashx do you guys have any plans to curate more ES6 code examples?

**Comment by odoe** [comment]
We'll revisit this, as our samples need to be able to run as-is in the browser in most cases. So probably not fat arrow functions, but could do some other stuff.

**Comment by sanmolhec** [comment]
As far as we know, ES6 already works in most of the current browsers -[http://kangax.github.io/compat-table/es6/](http://kangax.github.io/compat-table/es6/)- with the exception of Internet Explorer (browser completely discouraged, among other things because Microsoft wants to "kill" and because they will not evolve it further, moreover ES6 does not seem to work there ever).
	
So, if ES6 already works in most browsers and IE probably will never work, wouldn't all the examples work with ES6 syntax? (I'm sure we are missing something crucial, but we don't know what) (We understand the complexity and the amount of resources that should be devoted to this, but wouldn't it be technically possible to make all the examples with the new syntax?

Greetings, Héctor.

**Comment by odoe** [comment]
Unfortunately, we have an obligation to support IE11, even in the samples.

**Comment by sanmolhec** [comment]
Okay, all right, if there are obligations or impositions there's no other way, that's a lost war...

We will wait to see if you can give us some pills (examples) of ES6. 

Thanks a lot.

Regards, Héctor.
