### ISSUE TITLE
New resource page for D3.js

### ISSUE THREAD

**Issue by hhkaos** [hhkaos/awesome-arcgis#29]
I would like to have a new resource page about this topic. Should we ask [the experts](https://esri-es.github.io/arcgis-experts/?topic=d3) to check if they can help us with this?.

We should start adding the [resource page template](RESOURCE_PAGE_TEMPLATE.md). I have checked the [project structure](https://github.com/hhkaos/awesome-arcgis/blob/master/SUMMARY.md) and I think this page should be placed under "**[Front-end](https://github.com/hhkaos/awesome-arcgis/blob/master/front-end/technologies/README.md)**" section.

Cheers!

**Comment by ntkog** [comment]
Of course , I'll send a pull request today. Cheers!

**Comment by ntkog** [comment]
Done!  Here you have it [https://github.com/hhkaos/awesome-arcgis/pull/30](https://github.com/hhkaos/awesome-arcgis/pull/30)

**Comment by ntkog** [comment]
Merged!
