### ISSUE TITLE
Add RSS Plugin

### ISSUE THREAD

**Issue by hhkaos** [hhkaos/awesome-arcgis#40]
Install: [gitbook-plugin-rss](https://github.com/denysdovhan/gitbook-plugin-rss)

**Comment by ntkog** [comment]
Finally we insalled gitbook-plugin-feed 

It supports Atom feeds too, and It's simpler

**Comment by hhkaos** [comment]
Cool it's already merge, thx!!

 I'll close this issue an open a new one with a bug I've found.
