### ISSUE TITLE
Third Party Libraries Page?

### ISSUE THREAD

**Issue by mpayson** [hhkaos/awesome-arcgis#9]
I think it'd be helpful to maintain a list of helpful 3rd party libraries for specific functionalities (eg not core front-end technologies like React). Thoughts? And where should it go? Maybe a new "Third Party" folder under "Front End"? Happy to create the PR.

Thought of this because I was pointed to a third-party clustering library for 4.4 ArcGIS js api that other people may appreciate until functionality is added to the core api and I'm not sure where to put it.

@hhkaos

**Comment by hhkaos** [comment]
Ey Max!, sorry I didn't see this issue before ^_^'', I have just re-configured my github notifications....

There is already a something like this, check [this page](https://esri-es.github.io/awesome-arcgis/front-end/technologies/), do you mean something like this?

Cheers!
